# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\Resources\Data Team\Mihir Test\Projects\Project sort\Sort_Main Page.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 36, 762, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(120, 160, 101, 21))
        self.label.setObjectName("label")
        self.AutoNumOfInputs = QtWidgets.QLineEdit(self.groupBox_2)
        self.AutoNumOfInputs.setGeometry(QtCore.QRect(210, 160, 61, 20))
        self.AutoNumOfInputs.setObjectName("AutoNumOfInputs")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 121, 21))
        self.label_2.setObjectName("label_2")
        self.UserInputLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.UserInputLine.setGeometry(QtCore.QRect(150, 40, 541, 20))
        self.UserInputLine.setObjectName("UserInputLine")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(30, 70, 661, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(250, 100, 191, 21))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(470, 120, 231, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.label_5.setObjectName("label_5")
        self.AutoRangeStart = QtWidgets.QLineEdit(self.groupBox)
        self.AutoRangeStart.setGeometry(QtCore.QRect(40, 30, 51, 20))
        self.AutoRangeStart.setObjectName("AutoRangeStart")
        self.AutoRangeEnd = QtWidgets.QLineEdit(self.groupBox)
        self.AutoRangeEnd.setGeometry(QtCore.QRect(40, 70, 51, 20))
        self.AutoRangeEnd.setObjectName("AutoRangeEnd")
        self.SubmitButton = QtWidgets.QPushButton(self.groupBox)
        self.SubmitButton.setGeometry(QtCore.QRect(80, 100, 75, 23))
        self.SubmitButton.setObjectName("SubmitButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 323, 762, 150))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.label_6.setObjectName("label_6")
        self.SelectSort = QtWidgets.QComboBox(self.groupBox_3)
        self.SelectSort.setGeometry(QtCore.QRect(130, 40, 91, 22))
        self.SelectSort.setObjectName("SelectSort")
        self.SelectSort.addItem("")
        self.SelectSort.addItem("")
        self.SelectSort.addItem("")
        self.SelectSort.addItem("")
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(250, 30, 16, 81))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(290, 30, 151, 16))
        self.label_7.setObjectName("label_7")
        self.SelectVisual = QtWidgets.QComboBox(self.groupBox_3)
        self.SelectVisual.setGeometry(QtCore.QRect(440, 30, 141, 22))
        self.SelectVisual.setObjectName("SelectVisual")
        self.RunSimulation = QtWidgets.QPushButton(self.frame)
        self.RunSimulation.setGeometry(QtCore.QRect(340, 490, 80, 21))
        self.RunSimulation.setObjectName("RunSimulation")
        self.Cancel = QtWidgets.QPushButton(self.frame)
        self.Cancel.setGeometry(QtCore.QRect(630, 490, 80, 21))
        self.Cancel.setObjectName("Cancel")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Input Selection"))
        self.label.setText(_translate("MainWindow", "Number of Inputs"))
        self.label_2.setText(_translate("MainWindow", "Enter the values to sort:"))
        self.label_3.setText(_translate("MainWindow", "Generate Random numbers for Sorting"))
        self.groupBox.setTitle(_translate("MainWindow", "Range of Inputs"))
        self.label_4.setText(_translate("MainWindow", "Start:"))
        self.label_5.setText(_translate("MainWindow", "End:"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sort and Visualization "))
        self.label_6.setText(_translate("MainWindow", "Select a Sorting Method:"))
        self.SelectSort.setItemText(0, _translate("MainWindow", "Quick Sort"))
        self.SelectSort.setItemText(1, _translate("MainWindow", "Selection Sort"))
        self.SelectSort.setItemText(2, _translate("MainWindow", "Merge Sort"))
        self.SelectSort.setItemText(3, _translate("MainWindow", "Bubble Sort"))
        self.label_7.setText(_translate("MainWindow", "Select a type of visualization :"))
        self.RunSimulation.setText(_translate("MainWindow", "Run Simulation"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

